# <u>**Part 4**

In [1]:
import numpy as np

### **Exercise 31**

Consider the following array

[[4.99, 3.49, 9.99],<br>
[1.99, 9.99, 4.99],<br>
[14.99, 2.39, 7.29]]

sort this array:

* by row (ascending)
* by column (ascending)



In [2]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [5]:
# by column
np.sort(A, axis=0)

array([[ 1.99,  2.39,  4.99],
       [ 4.99,  3.49,  7.29],
       [14.99,  9.99,  9.99]])

In [6]:
# by row
np.sort(A, axis=1)

array([[ 3.49,  4.99,  9.99],
       [ 1.99,  4.99,  9.99],
       [ 2.39,  7.29, 14.99]])

### **Exercise 32**

Consider the following array

[[4.99, 3.49, 9.99],<br>
[1.99, 9.99, 4.99],<br>
[14.99, 2.39, 7.29]]

Extract all elements from the following array with a value greater than 8.

In [7]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [8]:
A > 8

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])

In [9]:
A[A > 8]

array([ 9.99,  9.99, 14.99])

### **Exercise 33**

Consider the following array

[[4.99, 3.49, 9.99],<br>
[1.99, 9.99, 4.99],<br>
[14.99, 2.39, 7.29]]

Replace elements greater than 10 with a fixed value = 10.0

In [10]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [13]:
B = np.where(A>10, 10, A)
B

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99,  4.99],
       [10.  ,  2.39,  7.29]])

### **Exercise 34**

Consider the following array

[[4.99, 3.49, 9.99],<br>
[1.99, 9.99, 4.99],<br>
[14.99, 2.39, 7.29]]

Present the following two-dimensional array as a flattened one-dimensional array.





In [14]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [15]:
np.ravel(A)

array([ 4.99,  3.49,  9.99,  1.99,  9.99,  4.99, 14.99,  2.39,  7.29])

### **Exercise 35**

Consider the following array

[[4.99, 3.49, 9.99],<br>
[1.99, 9.99, 4.99],<br>
[14.99, 2.39, 7.29]

Using Numpy create an array of the same shape and data type as the given array and fill it with zeros.

In [16]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [17]:
B = np.zeros_like(A)
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### **Exercise 36**

Consider the following array

[[4.99, 3.49, 9.99],<br>
[1.99, 9.99, 4.99],<br>
[14.99, 2.39, 7.29]

Using Numpy create an array of the same shape and data type as the given array and fill it with a constant value = 9.99

In [19]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [20]:
B = np.full_like(A, 9.99)
B

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

### **Exercise 37**

Using Numpy create a two-dimensional array (lower triangular matrix):

[[1, 0, 0, 0, 0],<br>
[1, 1, 0, 0, 0],<br>
[1, 1, 1, 0, 0], <br>
[1, 1, 1, 1, 0], <br>
[1, 1, 1, 1, 1]]



In [21]:
A = np.tri(5, 5, 0)
A

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

### **Excercise 38**

Using Numpy create any 3-dimensional array with shape (2, 3, 4) and assign to variable A.

In [22]:
A = np.array([[[4, 5, 4, 2],
               [6, 3, 5, 1],
               [5, 2, 1, 2]],
              
              [[7, 2, 3, 1],
               [6, 2, 0, 9],
               [0, 1, 9, 1]]])
A

array([[[4, 5, 4, 2],
        [6, 3, 5, 1],
        [5, 2, 1, 2]],

       [[7, 2, 3, 1],
        [6, 2, 0, 9],
        [0, 1, 9, 1]]])

### **Exercise 39**

Using Numpy create a two-dimensional array with shape of (200, 300) filled with random values from 0 to 255 (inclusive) with data type np.uint8 and assign to the variable image.



In [25]:
image = np.random.randint(low = 0,
                            high = 256,
                            size = (200,300),
                            dtype=np.uint8
                            )
image

array([[ 13,  67, 104, ..., 199, 113, 126],
       [243, 166, 237, ..., 147, 248,  94],
       [  9,   7, 135, ..., 209, 213,  59],
       ...,
       [ 56, 163, 172, ..., 136,  44,  78],
       [ 28, 150, 191, ..., 148, 182, 207],
       [142, 158, 153, ...,  78, 188, 141]], dtype=uint8)

### **Exercise 40**

consider the following array

image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)

Sort this array along the rows in ascending order and assign to the variable image_sorted.

In [26]:
image = np.random.randint(low = 0,
                            high = 256,
                            size = (200,300),
                            dtype=np.uint8
                            )

image

array([[ 61, 223, 152, ...,  46,  40, 245],
       [ 58, 226,  60, ...,  24,  81,  95],
       [142, 114, 127, ..., 134, 118,  42],
       ...,
       [123,  96, 223, ..., 236,  56, 209],
       [187, 103,  56, ..., 175, 137,  41],
       [ 69,  84,  10, ..., 172, 252,  95]], dtype=uint8)

In [28]:
image_sorted = np.sort(image, axis=1)
image_sorted

array([[  1,   1,   1, ..., 253, 254, 255],
       [  3,   4,   4, ..., 253, 253, 254],
       [  2,   3,   4, ..., 255, 255, 255],
       ...,
       [  0,   0,   0, ..., 251, 251, 255],
       [  1,   2,   3, ..., 251, 252, 252],
       [  3,   3,   3, ..., 252, 254, 255]], dtype=uint8)